events {
    worker_connections 1024;
}

http {
    upstream barnaba {
        server cli2rest-barnaba:8000;
    }
    upstream bpnet {
        server cli2rest-bpnet:8000;
    }
    upstream fr3d {
        server cli2rest-fr3d:8000;
    }
    upstream inkscape {
        server cli2rest-inkscape:8000;
    }
    upstream maxit {
        server cli2rest-maxit:8000;
    }
    upstream mc-annotate {
        server cli2rest-mc-annotate:8000;
    }
    upstream rchie {
        server cli2rest-rchie:8000;
    }
    upstream rnaview {
        server cli2rest-rnaview:8000;
    }
    upstream varna-tz {
        server cli2rest-varna-tz:8000;
    }

    server {
        listen 80;
        resolver 127.0.0.11 valid=10s;

        location /cli2rest-barnaba/ {
            proxy_pass http://barnaba/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-bpnet/ {
            proxy_pass http://bpnet/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-fr3d/ {
            proxy_pass http://fr3d/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-inkscape/ {
            proxy_pass http://inkscape/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-maxit/ {
            proxy_pass http://maxit/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-mc-annotate/ {
            proxy_pass http://mc-annotate/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-rchie/ {
            proxy_pass http://rchie/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-rnaview/ {
            proxy_pass http://rnaview/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location /cli2rest-varna-tz/ {
            proxy_pass http://varna-tz/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        location / {
            return 200;
        }
    }
}
