name: Docker Image CI v2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}

    env:
      DOCKER_IMAGE: rnapdbee-image
      DOCKER_CONTAINER: rnapdbee-container

    steps:
      - uses: actions/checkout@v3

      - name: Build the docker image
        run: DOCKER_BUILDKIT=1 docker build --progress=plain --target server -t $DOCKER_IMAGE .

      - name: Create the docker container
        run: |
          docker create --name $DOCKER_CONTAINER --env-file .env $DOCKER_IMAGE

      - name: Start the docker container
        run: docker start $DOCKER_CONTAINER

      - name: Copy files
        run: |
          docker cp tests/ $DOCKER_CONTAINER:rnapdbee-adapters/src/
          docker cp test_requirements.txt $DOCKER_CONTAINER:/

      - name: Install test requirements
        run: docker exec $DOCKER_CONTAINER bin/bash -c "pip3 install -r test_requirements.txt"

      - name: Run test
        run: |
          docker exec $DOCKER_CONTAINER bin/bash -c "cd ./rnapdbee-adapters/src/tests && pytest -v --cov='adapters'"

  lint:
    runs-on: ubuntu-22.04
    if: ${{ github.actor != 'dependabot[bot]' }}

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r test_requirements.txt

      - name: Analyze with pylint
        run: pylint --rcfile pylintrc src/
